package ccswitch

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// ImportProvider describes one provider in an import file. The snake_case
// aliases are accepted so files can be generated by shell scripts easily.
type ImportProvider struct {
	App             string `json:"app,omitempty" yaml:"app,omitempty"`
	AppType         string `json:"app_type,omitempty" yaml:"app_type,omitempty"`
	Name            string `json:"name,omitempty" yaml:"name,omitempty"`
	BaseURL         string `json:"baseURL,omitempty" yaml:"baseURL,omitempty"`
	BaseURLSnake    string `json:"base_url,omitempty" yaml:"base_url,omitempty"`
	APIKey          string `json:"apiKey,omitempty" yaml:"apiKey,omitempty"`
	APIKeySnake     string `json:"api_key,omitempty" yaml:"api_key,omitempty"`
	Model           string `json:"model,omitempty" yaml:"model,omitempty"`
	ReasoningEffort string `json:"reasoningEffort,omitempty" yaml:"reasoningEffort,omitempty"`
	ReasoningSnake  string `json:"reasoning_effort,omitempty" yaml:"reasoning_effort,omitempty"`
	Website         string `json:"website,omitempty" yaml:"website,omitempty"`
	Notes           string `json:"notes,omitempty" yaml:"notes,omitempty"`
}

func (p ImportProvider) appName() string {
	if strings.TrimSpace(p.App) != "" {
		return p.App
	}
	return p.AppType
}

func (p ImportProvider) input() ProviderInput {
	baseURL := p.BaseURL
	if strings.TrimSpace(baseURL) == "" {
		baseURL = p.BaseURLSnake
	}
	apiKey := p.APIKey
	if strings.TrimSpace(apiKey) == "" {
		apiKey = p.APIKeySnake
	}
	reasoningEffort := p.ReasoningEffort
	if strings.TrimSpace(reasoningEffort) == "" {
		reasoningEffort = p.ReasoningSnake
	}
	return ProviderInput{
		Name:            p.Name,
		BaseURL:         baseURL,
		APIKey:          apiKey,
		Model:           p.Model,
		ReasoningEffort: reasoningEffort,
		Website:         p.Website,
		Notes:           p.Notes,
	}
}

type importDocument struct {
	Providers []ImportProvider `json:"providers,omitempty" yaml:"providers,omitempty"`
	Claude    []ImportProvider `json:"claude,omitempty" yaml:"claude,omitempty"`
	Codex     []ImportProvider `json:"codex,omitempty" yaml:"codex,omitempty"`
	Gemini    []ImportProvider `json:"gemini,omitempty" yaml:"gemini,omitempty"`
	Grok      []ImportProvider `json:"grok,omitempty" yaml:"grok,omitempty"`
	Opencode  []ImportProvider `json:"opencode,omitempty" yaml:"opencode,omitempty"`
}

type ImportResult struct {
	Imported []string
	Updated  []string
	Failed   []string
}

type ExportOptions struct {
	RedactSecrets bool
}

func (r ImportResult) Error() error {
	if len(r.Failed) == 0 {
		return nil
	}
	return fmt.Errorf("%d 个供应商导入失败", len(r.Failed))
}

// ImportProviderFile reads a JSON/YAML provider bundle and imports every valid
// entry through the normal provider creation path.
func (s *Store) ImportProviderFile(path string) (ImportResult, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return ImportResult{}, fmt.Errorf("读取导入文件失败: %w", err)
	}
	providers, err := parseImportDocument(path, data)
	if err != nil {
		return ImportResult{}, fmt.Errorf("解析导入文件失败: %w", err)
	}
	if len(providers) == 0 {
		return ImportResult{}, errors.New("导入文件中没有供应商")
	}

	result := ImportResult{}
	for index, item := range providers {
		app, err := ParseAppType(item.appName())
		if err != nil {
			result.Failed = append(result.Failed, fmt.Sprintf("第 %d 项: %v", index+1, err))
			continue
		}
		input := item.input()
		providers, err := s.ListProviders(app)
		if err != nil {
			result.Failed = append(result.Failed, fmt.Sprintf("%s/%s: %v", app.DisplayName(), item.Name, err))
			continue
		}
		if existing := providerByName(providers, input.Name); existing != nil {
			if _, err := s.UpdateProvider(app, *existing, input); err != nil {
				result.Failed = append(result.Failed, fmt.Sprintf("%s/%s: %v", app.DisplayName(), item.Name, err))
				continue
			}
			result.Updated = append(result.Updated, fmt.Sprintf("%s/%s", app.DisplayName(), existing.Name))
			continue
		}
		created, _, err := s.AddProvider(app, input)
		if err != nil {
			result.Failed = append(result.Failed, fmt.Sprintf("%s/%s: %v", app.DisplayName(), item.Name, err))
			continue
		}
		result.Imported = append(result.Imported, fmt.Sprintf("%s/%s", app.DisplayName(), created.Name))
	}
	return result, result.Error()
}

func providerByName(providers []Provider, name string) *Provider {
	name = strings.TrimSpace(name)
	if name == "" {
		return nil
	}
	for index := range providers {
		if strings.EqualFold(strings.TrimSpace(providers[index].Name), name) {
			provider := providers[index]
			return &provider
		}
	}
	return nil
}

// ExportProviderFile writes all providers in the normalized import format.
// Unless RedactSecrets is enabled, the output can be imported directly.
func (s *Store) ExportProviderFile(path string, options ExportOptions) (int, error) {
	providers := make([]ImportProvider, 0)
	for _, app := range AllAppTypes {
		items, err := s.ListProviders(app)
		if err != nil {
			return 0, err
		}
		for _, provider := range items {
			input := s.ExtractInput(app, provider)
			apiKey := input.APIKey
			if options.RedactSecrets {
				apiKey = "[REDACTED]"
			}
			providers = append(providers, ImportProvider{
				App:            app.String(),
				Name:           input.Name,
				BaseURLSnake:   input.BaseURL,
				APIKeySnake:    apiKey,
				Model:          input.Model,
				ReasoningSnake: input.ReasoningEffort,
				Website:        input.Website,
				Notes:          input.Notes,
			})
		}
	}
	if len(providers) == 0 {
		return 0, errors.New("没有可导出的供应商")
	}

	document := importDocument{Providers: providers}
	var data []byte
	var err error
	switch strings.ToLower(filepath.Ext(path)) {
	case ".json":
		data, err = json.MarshalIndent(document, "", "  ")
	case ".yaml", ".yml":
		data, err = yaml.Marshal(document)
	default:
		return 0, fmt.Errorf("不支持的导出文件后缀 %q，仅支持 .json、.yml、.yaml", filepath.Ext(path))
	}
	if err != nil {
		return 0, fmt.Errorf("生成导出文件失败: %w", err)
	}
	if err := writeExportFile(path, data); err != nil {
		return 0, err
	}
	return len(providers), nil
}

func writeExportFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("创建导出目录失败: %w", err)
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".cctui-export-*")
	if err != nil {
		return fmt.Errorf("创建导出临时文件失败: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o600); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("设置导出文件权限失败: %w", err)
	}
	if _, err := temporary.Write(data); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("写入导出文件失败: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("同步导出文件失败: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("关闭导出文件失败: %w", err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("保存导出文件失败: %w", err)
	}
	return nil
}

func parseImportDocument(path string, data []byte) ([]ImportProvider, error) {
	var document importDocument
	switch strings.ToLower(filepath.Ext(path)) {
	case ".json":
		if err := json.Unmarshal(data, &document); err != nil {
			var providers []ImportProvider
			if listErr := json.Unmarshal(data, &providers); listErr != nil {
				return nil, err
			}
			return providers, nil
		}
	case ".yaml", ".yml":
		if err := yaml.Unmarshal(data, &document); err != nil {
			var providers []ImportProvider
			if listErr := yaml.Unmarshal(data, &providers); listErr != nil {
				return nil, err
			}
			return providers, nil
		}
	default:
		return nil, fmt.Errorf("不支持的导入文件后缀 %q，仅支持 .json、.yml、.yaml", filepath.Ext(path))
	}
	providers := append([]ImportProvider(nil), document.Providers...)
	providers = appendGroupedImportProviders(providers, AppClaude, document.Claude)
	providers = appendGroupedImportProviders(providers, AppCodex, document.Codex)
	providers = appendGroupedImportProviders(providers, AppGemini, document.Gemini)
	providers = appendGroupedImportProviders(providers, AppGrok, document.Grok)
	providers = appendGroupedImportProviders(providers, AppOpencode, document.Opencode)
	return providers, nil
}

func appendGroupedImportProviders(dst []ImportProvider, app AppType, grouped []ImportProvider) []ImportProvider {
	for index := range grouped {
		if strings.TrimSpace(grouped[index].appName()) == "" {
			grouped[index].App = app.String()
		}
		dst = append(dst, grouped[index])
	}
	return dst
}
